### ISSUE TITLE
Consider creating an about page

### ISSUE THREAD

**Issue by boazsender** [bocoup/ajl.ai#203]
Based on feedback from the crit with the @Bocoup AI Now team (@iamjessklein @iros ):

Consider creating an additional about page with:
* image of the team
* explanation of why the team is working on this project
* Assumptions the project makes
* Why this dataset? 
* Project timeline
* How are you sharing the results of this experiment 
* What are the research questions? 

Add similar description to readme.

**Comment by iamjessklein** [comment]
+1 to README being more extensive.

**Comment by boazsender** [comment]
This was completed via earlier commits by myself to the readme, and @joyab's work in #248.
